'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { GitGovernance } = require('../plugin/git');
async function fixture(t) {
    const root = await fs.mkdtemp(path.join(process.env.PI_SCRATCH_DIR || os.tmpdir(), 'git-governance-'));
    t.after(() => fs.rm(root, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 }));
    const g = new GitGovernance(root);
    await g.git(root, ['init', '-b', 'main']);
    await g.git(root, ['config', 'user.name', 'Governance Test']);
    await g.git(root, ['config', 'user.email', 'test@example.invalid']);
    await g.git(root, ['config', 'core.autocrlf', 'false']);
    await fs.writeFile(path.join(root, 'a.txt'), 'base\n');
    await fs.writeFile(path.join(root, 'b.txt'), 'base b\n');
    await g.git(root, ['add', 'a.txt', 'b.txt']);
    await g.git(root, ['commit', '-m', 'base']);
    const base = await g.head(root);
    const create = (id, options = {}) => g.run({ action: 'git_create', id, owner: id, role: 'coordinator', goal: 'Implement approved change', criteria: ['Checked'], allowedPaths: ['a.txt', 'b.txt', 'docs/'], expectedHead: base, ...options });
    const commit = async (task) => { const d = await g.run({ action: 'git_diff', id: task.id }); return g.run({ action: 'git_commit', id: task.id, message: 'task change', expectedDiff: d.snapshot }); };
    const verify = async (task) => g.run({ action: 'git_verify', id: task.id, expectedHead: await g.head(task.worktree), passed: true, accepted: [true], evidence: 'Fixture assertions executed', diffReview: 'Fixture diff checked' });
    const integrate = async (parent, child) => g.run({ action: 'git_integrate', id: parent.id, source: child.id, expectedHead: await g.head(parent.worktree), sourceHead: await g.head(child.worktree) });
    return { root, g, base, create, commit, verify, integrate };
}
test('isolated worktrees, commit-bound verification and coordinator integration', async (t) => {
    const { root, g, base, create, commit, verify, integrate } = await fixture(t);
    const parent = await create('parent');
    const a = await create('worker-a', { role: 'worker', parent: parent.id, allowedPaths: ['a.txt'] });
    const b = await create('worker-b', { role: 'worker', parent: parent.id, allowedPaths: ['b.txt'] });
    assert.notEqual(a.worktree, b.worktree);
    await fs.writeFile(path.join(a.worktree, 'a.txt'), 'worker a\n');
    assert.equal(await fs.readFile(path.join(root, 'a.txt'), 'utf8'), 'base\n');
    assert.equal(await fs.readFile(path.join(b.worktree, 'a.txt'), 'utf8'), 'base\n');
    await commit(a);
    await assert.rejects(integrate(parent, a), /verification stale/);
    await verify(a);
    await integrate(parent, a);
    await fs.writeFile(path.join(b.worktree, 'b.txt'), 'worker b\n');
    await commit(b);
    await verify(b);
    await integrate(parent, b);
    assert.equal(await fs.readFile(path.join(parent.worktree, 'a.txt'), 'utf8'), 'worker a\n');
    assert.equal(await fs.readFile(path.join(parent.worktree, 'b.txt'), 'utf8'), 'worker b\n');
    assert.equal(await g.head(root), base);
    const newAgent = new GitGovernance(root);
    let state = await newAgent.run({ action: 'git_status' });
    assert.equal(state.tasks.find(x => x.id === 'parent').verificationValid, false);
    await verify(parent);
    state = await newAgent.run({ action: 'git_status' });
    assert.equal(state.tasks.find(x => x.id === 'parent').verificationValid, true);
    assert.equal(state.tasks.find(x => x.id === a.id).status, 'integrated');
});
test('dirty base and invalid scope cannot create a worktree', async (t) => {
    const { root, create } = await fixture(t);
    await fs.writeFile(path.join(root, 'user.txt'), 'preserve');
    await assert.rejects(create('dirty'), /dirty/);
    assert.equal(await fs.readFile(path.join(root, 'user.txt'), 'utf8'), 'preserve');
    for (const p of ['../escape', '.', '.git/', 'docs/*', 'C:/escape'])
        await assert.rejects(create('bad', { allowedPaths: [p] }), /Unsafe/);
});
test('worker scopes cannot overlap or include shared state', async (t) => {
    const { create } = await fixture(t);
    const p = await create('parent', { allowedPaths: ['docs/', 'STATE.json'] });
    await create('a', { role: 'worker', parent: p.id, allowedPaths: ['docs/'] });
    await assert.rejects(create('b', { role: 'worker', parent: p.id, allowedPaths: ['docs/readme.md'] }), /overlap/);
    await assert.rejects(create('c', { role: 'worker', parent: p.id, allowedPaths: ['STATE.json'] }), /shared state/);
});
test('out-of-scope, stale diff and stale commit evidence are rejected', async (t) => {
    const { g, create, commit, verify, integrate } = await fixture(t);
    const p = await create('parent');
    const w = await create('worker', { role: 'worker', parent: p.id, allowedPaths: ['a.txt'] });
    await fs.writeFile(path.join(w.worktree, 'b.txt'), 'outside');
    await assert.rejects(g.run({ action: 'git_diff', id: w.id }), /Out-of-scope/);
    await fs.writeFile(path.join(w.worktree, 'b.txt'), 'base b\n');
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'one');
    const d = await g.run({ action: 'git_diff', id: w.id });
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'two');
    await assert.rejects(g.run({ action: 'git_commit', id: w.id, expectedDiff: d.snapshot, message: 'stale' }), /Diff changed/);
    await commit(w);
    await verify(w);
    // A direct Git commit bypasses the plugin but still invalidates integration evidence.
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'three');
    await g.git(w.worktree, ['add', 'a.txt']);
    await g.git(w.worktree, ['commit', '-m', 'external']);
    await assert.rejects(integrate(p, w), /verification stale/);
});
test('renames, deletions, new files and reverting to base are tracked', async (t) => {
    const { g, create, commit } = await fixture(t);
    const p = await create('parent', { allowedPaths: ['a.txt', 'b.txt', 'renamed.txt', 'new file.txt'] });
    await fs.rename(path.join(p.worktree, 'a.txt'), path.join(p.worktree, 'renamed.txt'));
    await fs.rm(path.join(p.worktree, 'b.txt'));
    await fs.writeFile(path.join(p.worktree, 'new file.txt'), 'new');
    const d = await g.run({ action: 'git_diff', id: p.id });
    assert.deepEqual(d.files, ['a.txt', 'b.txt', 'new file.txt', 'renamed.txt']);
    await commit(p);
    await fs.writeFile(path.join(p.worktree, 'new file.txt'), 'second');
    await commit(p);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'base\n');
    await commit(p);
    assert.equal(await fs.readFile(path.join(p.worktree, 'a.txt'), 'utf8'), 'base\n');
});
test('conflicts are preserved, staged resolution can be committed and reverified', async (t) => {
    const { g, create, commit, verify, integrate } = await fixture(t);
    const p = await create('parent');
    const w = await create('worker', { role: 'worker', parent: p.id, allowedPaths: ['a.txt'] });
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'worker\n');
    await commit(w);
    await verify(w);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'parent\n');
    await commit(p);
    const result = await integrate(p, w);
    assert.equal(result.ok, false);
    assert.equal(await g.merging(p.worktree), true);
    assert.match(await fs.readFile(path.join(p.worktree, 'a.txt'), 'utf8'), /<<<<<<</);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'resolved\n');
    await g.git(p.worktree, ['add', 'a.txt']);
    await commit(p);
    await verify(p);
    assert.equal(await g.merging(p.worktree), false);
});
test('manual merge abort can recover metadata without discarding files', async (t) => {
    const { g, create, commit, verify, integrate } = await fixture(t);
    const p = await create('parent');
    const w = await create('worker', { role: 'worker', parent: p.id, allowedPaths: ['a.txt'] });
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'worker\n');
    await commit(w);
    await verify(w);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'parent\n');
    await commit(p);
    await integrate(p, w);
    await g.git(p.worktree, ['merge', '--abort']);
    const recovered = await g.run({ action: 'git_recover', id: p.id, expectedHead: await g.head(p.worktree) });
    assert.equal(recovered.merged, false);
    assert.equal(await fs.readFile(path.join(p.worktree, 'a.txt'), 'utf8'), 'parent\n');
});
test('successful merge interrupted before registry save can recover', async (t) => {
    const { g, create, commit, verify, integrate } = await fixture(t);
    const p = await create('parent');
    const w = await create('worker', { role: 'worker', parent: p.id, allowedPaths: ['a.txt'] });
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'worker\n');
    await commit(w);
    await verify(w);
    const save = g.save.bind(g);
    let calls = 0;
    g.save = async (data) => { if (++calls === 2)
        throw Error('simulated interruption'); return save(data); };
    await assert.rejects(integrate(p, w), /interruption/);
    g.save = save;
    assert.equal((await g.run({ action: 'git_recover', id: p.id, expectedHead: await g.head(p.worktree) })).merged, true);
});
test('missing repository and unexpected branch fail safely', async (t) => {
    const { g, create } = await fixture(t);
    const p = await create('parent');
    await g.git(p.worktree, ['switch', '-c', 'unexpected']);
    await assert.rejects(g.run({ action: 'git_diff', id: p.id }), /branch changed/);
    const dir = await fs.mkdtemp(path.join(process.env.PI_SCRATCH_DIR || os.tmpdir(), 'not-git-'));
    t.after(() => fs.rm(dir, { recursive: true, force: true }));
    await assert.rejects(new GitGovernance(dir).run({ action: 'git_status' }), /git rev-parse failed/);
});
test('merge resolution identical to coordinator still creates a merge commit', async (t) => {
    const { g, create, commit, verify, integrate } = await fixture(t);
    const p = await create('parent');
    const w = await create('worker', { role: 'worker', parent: p.id, allowedPaths: ['a.txt'] });
    await fs.writeFile(path.join(w.worktree, 'a.txt'), 'worker\n');
    await commit(w);
    await verify(w);
    const workerHead = await g.head(w.worktree);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'parent\n');
    await commit(p);
    assert.equal((await integrate(p, w)).ok, false);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'parent\n');
    await g.git(p.worktree, ['add', 'a.txt']);
    assert.equal(await g.git(p.worktree, ['status', '--porcelain=v1']), '');
    await commit(p);
    await verify(p);
    assert.equal(await g.merging(p.worktree), false);
    await g.git(p.worktree, ['merge-base', '--is-ancestor', workerHead, 'HEAD']);
    assert.equal(await fs.readFile(path.join(p.worktree, 'a.txt'), 'utf8'), 'parent\n');
    const status = await g.run({ action: 'git_status' });
    assert.equal(status.tasks.find(x => x.id === w.id).status, 'integrated');
    assert.equal(status.tasks.find(x => x.id === p.id).verificationValid, true);
});
test('diff exposes a pending revert even when the net task patch is empty', async (t) => {
    const { g, create, commit } = await fixture(t);
    const p = await create('parent');
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'changed\n');
    await commit(p);
    await fs.writeFile(path.join(p.worktree, 'a.txt'), 'base\n');
    await g.git(p.worktree, ['add', 'a.txt']);
    const d = await g.run({ action: 'git_diff', id: p.id });
    assert.equal(d.patch, '');
    assert.match(d.workingPatch, /-changed/);
    assert.match(d.stagedPatch, /\+base/);
    await commit(p);
});
