'use strict';
const fs = require('node:fs');
const path = require('node:path');
const marker = '// Generated by scripts/build-entry.cjs. Do not edit.\n';
const content = marker + "'use strict';\nmodule.exports = require('./runtime/main.js');\n";
function check(root) {
  const plugin = path.join(root, 'plugin');
  const dir = fs.lstatSync(plugin);
  if (dir.isSymbolicLink() || !dir.isDirectory()) throw Error('Refusing linked plugin directory');
  const entry = path.join(plugin, 'main.js');
  let stat;
  try {
    stat = fs.lstatSync(entry);
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (stat) {
    if (stat.isSymbolicLink() || !stat.isFile()) throw Error('Refusing linked or non-file entry');
    if (!fs.readFileSync(entry, 'utf8').replace(/\r\n/g, '\n').startsWith(marker))
      throw Error('Refusing hand-written plugin entry');
  }
  return entry;
}
function generate(root) {
  fs.writeFileSync(check(root), content, 'utf8');
}
module.exports = { check, generate, content };
if (require.main === module) generate(path.resolve(__dirname, '..'));
